site/dat/wiki/Changelog.wiki, standard/src/kg/apc/jmeter/vizualizers/SynthesisReportGui.java
Hi,
I made some changes with the SynthesisReportGui :
The 90 percentile is now customizable with JMeter 2.13 and beyond.
It is fully compatible with both JMeter 2.11 (no change here, 90 percentile only) and JMeter 2.13 (customizable).
Regards,
Félix HENRY
=> The 90 percentile (historical behavior) is now customizable

extras/src/kg/apc/jmeter/listener/GraphsGeneratorListener.java, extras/src/kg/apc/jmeter/listener/GraphsGeneratorListenerResources.properties, site/dat/wiki/Changelog.wiki, site/dat/wiki/GraphsGeneratorListener.wiki
Hi @undera ,
Find here a PR that adds:
- SynthesisReport + AggregateReport to GraphsGeneratorListener as I find myself needing them nearly every time
-Adds BOTH to allow generation at the same time of CSV and PNG
Hope you can take it into account soon.
Regards
Philippe M.
@philmdot
=> Graphs Generator Listener Improvements

.travis.yml, common/pom.xml, extras/pom.xml, extras/src/kg/apc/jmeter/vizualizers/ConnectTimesOverTimeGui.java, extras/test/kg/apc/jmeter/vizualizers/ConnectTimesOverTimeGuiTest.java, extraslibs/pom.xml, hadoop/pom.xml, pom.xml, site/dat/tpl/plugins.tpl, site/dat/wiki/Changelog.wiki, site/dat/wiki/ConnectTimeOverTime.wiki, site/dat/wiki/ExtrasSet.wiki, site/dat/wiki/FlexibleFileWriter.wiki, site/dat/wiki/Start.wiki, standard/pom.xml, standard/src/kg/apc/jmeter/reporters/FlexibleFileWriter.java, standard/src/kg/apc/jmeter/reporters/FlexibleFileWriterGui.java, standard/test/kg/apc/jmeter/reporters/FlexibleFileWriterTest.java, webdriver/pom.xml
- FFW fiels
- over time graph
- something more?
=> Make use for connect times in JMeter

site/dat/wiki/Changelog.wiki, site/dat/wiki/FlexibleFileWriter.wiki, standard/src/kg/apc/jmeter/reporters/FlexibleFileWriter.java, standard/src/kg/apc/jmeter/reporters/FlexibleFileWriterGui.java
Add fields grpThreads sampleCount errorCount responseHeaderSize responseSize URL to FFW.
=> Adding additional field options.

extras/src/org/jmeterplugins/protocol/http/control/HttpSimpleTableServer.java, site/dat/wiki/Changelog.wiki
add header for response with no cache.
In the Changelog add links to documentation
=> Http Simple table server, no cache for Response add headers

extras/src/kg/apc/jmeter/jmxmon/JMXMonCollector.java, extras/src/kg/apc/jmeter/jmxmon/JMXMonConnectionPool.java, extras/src/kg/apc/jmeter/jmxmon/JMXMonSampler.java, extras/src/kg/apc/jmeter/vizualizers/JMXMonGui.java, extras/test/kg/apc/jmeter/jmxmon/JMXConnectorEmul.java, extras/test/kg/apc/jmeter/jmxmon/JMXMonConnectionPoolTest.java, extras/test/kg/apc/jmeter/jmxmon/JMXMonSuite.java, extras/test/kg/apc/jmeter/jmxmon/JMXMonTest.java, extras/test/kg/apc/jmeter/jmxmon/TestJMXMonCollector.java, extras/test/kg/apc/jmeter/jmxmon/rmi/ClientProvider.java, site/dat/wiki/Changelog.wiki, site/dat/wiki/Contributors.wiki, site/dat/wiki/JMXMon.wiki, webdriver/pom.xml
JMXMon.
Fixed a bug where all JMXMon samplers following a failing JMXMon sampler
were not created
Added test case, change changelog, contributors wiki page
=> Added new option to allow delayed connection or reconnection feature to

site/dat/wiki/JMeterPluginsCMD.wiki
DbMon and JMXMon are missing in Plugin Type
=> Add missing DbMon, JMXMon Plugin Type for JMeterPluginsCMD

plugins/jmxmon/src/main/java/kg/apc/jmeter/jmxmon/JMXMonCollector.java, plugins/jmxmon/src/main/java/kg/apc/jmeter/jmxmon/JMXMonSampler.java, plugins/jmxmon/src/test/java/kg/apc/jmeter/jmxmon/JMXMonSamplerTest.java, plugins/jmxmon/src/test/java/kg/apc/jmeter/jmxmon/JMeterPropertyEmul.java, plugins/jmxmon/src/test/java/kg/apc/jmeter/jmxmon/TestJMXMonCollector.java, site/dat/wiki/Changelog.wiki, site/dat/wiki/JMXMon.wiki
=> JMXmon url field can resolves jmeter variables defined during the test

site/dat/repo/various.json
As discussed with Andrey:
"..... So I encourage you to include your plugin into jmeter-plugins.org registry. To do so, you need to provide pull request ...." 
so here is my pull request.
Thanks for sharing this plugin with your community.
=> added Websocket Samplers plugin

tools/table-server/src/main/java/org/jmeterplugins/protocol/http/control/HttpSimpleTableServer.java, tools/table-server/src/test/java/org/jmeterplugins/protocol/http/control/HttpSimpleTableServerTest.java
Hi,
we would like to use STS as a global queue for JMeter threads, unfortunately, STS does not allow to do that because it does not maintain uniqueness of data being inserted.
=> Uniqueness support in STS

site/dat/wiki/HttpSimpleTableServer.wiki
=> Uniqueness support in STS, wiki update

site/dat/wiki/ConcurrencyThreadGroup.wiki
Added section explaining how to use with tstFeedback along with link to Schedule Feedback Function section in TST wiki page.
=> Add section on use with tstFeedback function

plugins/tst/src/main/java/kg/apc/jmeter/timers/VariableThroughputTimer.java, site/dat/wiki/ThroughputShapingTimer.wiki
This PR:
- Clarifies documentation a bit
- Provides some code cleanup and better logging
Regards
Philippe M.
@philmdot
=> Variable throughput timer code cleanup

plugins/webdriver/src/main/java/com/googlecode/jmeter/plugins/webdriver/sampler/WebDriverSampler.java, plugins/webdriver/src/main/java/com/googlecode/jmeter/plugins/webdriver/sampler/WebDriverScriptable.java, plugins/webdriver/src/main/java/com/googlecode/jmeter/plugins/webdriver/sampler/gui/WebDriverSamplerGui.java, site/dat/wiki/WebDriverSampler.wiki
This PR adds usual scripting variables:
WDS.vars
WDS.ctx
WDS.props
And allows to not override particular response code
Regards
Philippe M. from UbikLoadPack team
=> Enhance webdriver

site/dat/html/catalogue.html
This PR implements add the Maven information on the plugin card on website.
I don't know how to test if locally but the javascript part was tested, not the rendering.
Regards
Philippe M. from UbikLoadPack Team
=> Add Maven information to Plugin Card 

site/dat/repo/various.json
* Compelete refactor of the plugin
* Switched from OkHttp calls to native ElasticSearch 5.5.2 API Transport calls
* Fixed connection pool memory leak
* Added unit testing into the project
* Automatically add all dependencies on project packaging - easier install process.
* No more error class missing messages
=> Version 2.0.0 - ElasticSearch Backend Listener

site/dat/repo/various.json
changed download url to reflect that artifact is now available in maven repository
=> changed download url 

site/dat/repo/various.json
Rare null exception fix & removed useless fields
=> Version 2.0.2 - Rare null exception fix & removed useless fields

plugins/tst/src/main/java/kg/apc/jmeter/timers/VariableThroughputTimer.java, site/dat/wiki/ThroughputShapingTimer.wiki
As per discussion :
- https://groups.google.com/forum/#!topic/jmeter-plugins/U456alfPNBs
Regards
Philippe M.
=> Improve how Throughput Shaping Timer stops threads when ending

plugins/tst/src/main/java/kg/apc/jmeter/timers/VariableThroughputTimer.java
Hello,
This PR is just to make code a bit more readable (for me and I hope for others) before I submit another PR with a new little feature.
Hope you accept it.
Regards
Philippe M.
@philmdot
=> Improve documentation of class and variable namings

site/dat/repo/various.json
Currently causing issues : https://github.com/delirius325/jmeter-elasticsearch-backend-listener/issues/15
=> Forgot to change JAR (currently causing issues)

site/dat/repo/various.json
Fixed https://github.com/delirius325/jmeter-elasticsearch-backend-listener/issues/16
=> Version 2.2.2

site/dat/repo/various.json
New WSS Timestamp Pre-Processor
Add WSS UsernameToken timestamp precision option and no password option
=> WS Security Plugin Release 1.5

plugins/tst/src/main/java/kg/apc/jmeter/timers/VariableThroughputTimer.java, plugins/tst/src/main/java/kg/apc/jmeter/timers/VariableThroughputTimerGui.java, plugins/tst/src/test/java/kg/apc/jmeter/timers/VariableThroughputTimerTest.java
As per discussion:
https://groups.google.com/forum/#!searchin/jmeter-plugins/Throughput$20Shaping$20Timer$20$2F$20enhancements%7Csort:date/jmeter-plugins/U456alfPNBs/0YnJU0zJAAAJ
Regards
Philippe M.
@philmdot
=> Expose the duration of RPS which is sum of the last column Duration

plugins/tst/src/test/java/kg/apc/jmeter/timers/VariableThroughputTimerTest.java, site/dat/wiki/ThroughputShapingTimer.wiki
=> Add Junit for Exported Properties and improve formatting of my last submitted PR on docs

site/dat/repo/various.json
Cleaned up old versions at the same time
=> ES Backend Listener - 2.3.3

site/dat/repo/various.json
Fixed a problem with JavFX's class "StringConversion"
=> ElasticSearch Backend Listener version 2.4.3

site/dat/repo/various.json
* Switched to ES REST low-level client v6.4
* Removed deprecated methods usage
* Added support for sending custom variables to ES.
=> Version 2.5.0 - ES Backend Listener

site/dat/wiki/PluginRepositoryDescriptorFormat.wiki
Clarify installerClass behaviour
As per discussion:
- https://groups.google.com/forum/#!topic/jmeter-plugins/MyDFi8DcXw4
Find a PR that documents undocumented fields and clarifies others.
Regards
Philippe M.
=> Document missing fields.

site/dat/repo/various.json
Fixed issue https://github.com/delirius325/jmeter-elasticsearch-backend-listener/issues/36
=> 2.5.2 ES Listener

plugins/casutg/src/main/java/com/blazemeter/jmeter/threads/AbstractDynamicThreadGroup.java, plugins/casutg/src/main/java/com/blazemeter/jmeter/threads/AbstractDynamicThreadGroupModel.java, plugins/casutg/src/main/java/com/blazemeter/jmeter/threads/AbstractThreadStarter.java, plugins/casutg/src/main/java/com/blazemeter/jmeter/threads/concurrency/ConcurrencyThreadGroup.java, plugins/casutg/src/main/java/com/blazemeter/jmeter/threads/concurrency/ConcurrencyThreadStarter.java, plugins/casutg/src/test/java/com/blazemeter/jmeter/threads/concurrency/ConcurrencyThreadGroupTest.java, site/dat/wiki/ConcurrencyThreadGroup.wiki
As reported in:
- https://groups.google.com/forum/#!topic/jmeter-plugins/biuDmDSprFk
Improvements on CPU for same test:
Before : Avg:14.5%, Max : 99.1%
After : Avg : 8.53%, Max : 37%
If we zoom on first Minute:
Before : Avg:40%, Max : 99.1%
After : Avg : 17%, Max : 37%
=> Fix Concurrency Thread Group very high CPU issue

plugins/casutg/src/main/java/com/blazemeter/jmeter/threads/AbstractDynamicThreadGroupModel.java, plugins/casutg/src/main/java/com/blazemeter/jmeter/threads/concurrency/ConcurrencyThreadGroup.java
This should fix the NPE reported.
Sorry for this issue, there was no JUnit test covering this, so it was not caught.
Regards
Philippe M.
=> Fix NPE due to transient fields

site/dat/repo/blazemeter.json
This version fixes property naming for inputs by label feature
=> Add bzm-rte 1.1.1

site/dat/repo/blazemeter.json
Fixed HLS 1.3 release .json format
=> Fixed HLS 1.3 release .json format

site/dat/repo/various.json
Hello, new version coming :) changes:
1. new database scheme for ClickHouse
2. additional field in stats - hostname
=> 1.7 version for 'JMeter Listener pack'

plugins/casutg/pom.xml, plugins/casutg/src/main/java/com/blazemeter/jmeter/threads/AbstractDynamicThreadGroup.java, plugins/casutg/src/main/java/com/blazemeter/jmeter/threads/AbstractDynamicThreadGroupModel.java, plugins/casutg/src/main/java/com/blazemeter/jmeter/threads/AbstractThreadStarter.java, plugins/casutg/src/main/java/kg/apc/jmeter/threads/AbstractSimpleThreadGroup.java, plugins/casutg/src/test/java/com/blazemeter/jmeter/threads/arrivals/ArrivalsThreadGroupTest.java, plugins/casutg/src/test/java/kg/apc/jmeter/threads/AbstractSimpleThreadGroupImpl.java, plugins/casutg/src/test/java/kg/apc/jmeter/threads/AbstractSimpleThreadGroupTest.java, site/dat/repo/jpgc-plugins.json
Re https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jmeter-plugins/mEqossgJn2o/cInfSgbIBAAJ
=>  Respect JMeter's prefix for distributed threads

site/dat/repo/various.json
Fix https://github.com/delirius325/jmeter-elasticsearch-backend-listener/issues/60
=> ES Backend 2.6.8

site/dat/repo/blazemeter.json
• Update component classes in RTE-Plugin
• Screenshot update
=> RTE components update

site/dat/repo/various.json
This PR is to register our UbikLoadPack Video Streaming plugin so that it's available through jmeter-plugins-manager.
We think we have provided required elements, but let us know if anything is missing.
Kudos to all your OSS work for the JMeter community.
Thanks
Regards
=> Register UbikLoadPack Video Streaming plugin to JMeter-Plugins

site/dat/repo/blazemeter.json
Hello @undera 
This Pull Request is to register mqmeter plugin on jmeter-plugins-manager.
Thank you,
=> Add mqmeter JMeter plugin description.

site/dat/repo/blazemeter.json, site/dat/repo/various.json
Added support for MPED DASH and added new features.
=> Add HLS plugin 3.0 release

site/dat/repo/blazemeter.json, site/dat/repo/various.json
Added dependencies
* jackson-databind-2.10.2
* jackson-annotations-2.10.2
=> Added dependecies for support in JMeter 4

site/dat/repo/various.json
This PR is to publish the new version of UbikLoadPack Video Streaming plugin.
Regards
=> New version 6.6.0 of UbikLoadPack Video Streaming plugin for JMeter

site/dat/repo/blazemeter.json, site/dat/repo/various.json
Since the last screenshot URL became deprecated.
=> RTE Screenshot update

plugins/jmxmon/pom.xml, site/dat/repo/jpgc-plugins.json, site/dat/wiki/JMXMon.wiki
Follow on from PR #379 
Assuming there won't be a lot more changes anytime soon, this may as well be released?
=> Release new JMXMon version 0.3

site/dat/repo/various.json
I hope you're fine in current context.
This PR is to publish the new version of UbikLoadPack Video Streaming plugin.
Regards
=> New version 7.0.0 of UbikLoadPack Video Streaming plugin for JMeter

site/dat/repo/various.json
Thanks for merging 7.0.0.
This PR is to publish a bugfix version of UbikLoadPack Video Streaming plugin.
Regards
=> Release 7.0.1

site/dat/repo/various.json
This PR is to publish a minor enhancement + bugfix version of UbikLoadPack Video Streaming plugin.
Regards
=> Release 7.0.2

site/dat/repo/various.json
=> Ulp vs 7 1 0

site/dat/repo/various.json
I hope you are fine.
This PR is to publish UbikLoadPack Gwt plugin on JMeter-Plugins.
Regards
=> Release UbikLoadPack GWT Plugin 4.6.0 and publish to JMeter-Plugins Manager

site/dat/wiki/PluginsManager.wiki
Hello @undera , 
Sometimes Plugins Manager shows stale information.
This PR documents a way to fix this.
Regards
Philippe M.
https://ubikloadpack.com
=> Document existence and cleanup of plugin manager cache

site/dat/repo/various.json
=>  UbikLoadPack Video Streaming plugin Release 7.1.2

site/dat/repo/various.json
Regards
[UbikLoadPack Team](https://ubikloadpack.com/)
=> UbikLoadPack Video Streaming plugin Release 7.1.3

site/dat/repo/various.json
=> UbikLoadPack Video Streaming plugin Release 7.1.4

site/dat/repo/various.json
=> Release UbikLoadPack Video Streaming plugin 7.1.5

site/dat/repo/blazemeter.json
This patch release includes:
• Fix Master-Slave issue, related to RMI mechanism used by JMeter when running that type of test.
• Improve URL recognition.
=> HLS-Plugin v3.0.3

site/dat/repo/blazemeter.json
Removed a dependency (and keeping the version as it is)
=> Updated dependencies

site/dat/repo/blazemeter.json
Added support for Gzip in response headers 
Added data frame to PUT method
=> Added support for Gzip in response headers and modified PUT method

site/dat/repo/various.json
=> Release UbikLoadPack Video Streaming Plugin 7.1.7

site/dat/repo/blazemeter.json
New release for the Correlation Recorder Plugin v1.1
=> Correlation Recorder Release 1.1

site/dat/repo/blazemeter.json
* Improvements in the stability and performance.
* Increase in concurrent execution capacity.
* Improvements related to error information, information of status on Sampler result and detailed errors in log file
* Session windows is improved, better identification and position for better execution view
* New timeout parameters are incorporated (related to ica, connect, logoff and disconnect)
* The Logon Timeout parameter from the "Citrix Application Launcher" UI was removed
* The clause evaluation of "Citrix Application Launcher" now wait for the application start 
* Before disconnecting, a necessary logoff is performed to maintain a correct session state
* Hash handling precision is improved, parameters are also incorporated in case its precision needs to be changed
* …
=> Citrix-Plugin Release 0.6.0

site/dat/repo/blazemeter.json
Updated plugin screenshot, since the last was giving 404
=> Update Correlation Recorder plugin screenshot

site/dat/repo/various.json
=> Release UbikLoadPack Video Streaming plugin 7.1.8

site/dat/repo/various.json
=> Release UbikLoadPack Video Streaming plugin 7.1.9

site/dat/repo/various.json
=> Release UbikLoadPack Video Streaming plugin 7.2.0

site/dat/repo/blazemeter.json
Added the patch release v1.1.1 for Correlation Recorder
=> Add Correlation Recorder Patch Release 1.1.1

site/dat/repo/blazemeter.json
Release 0.7.0
* Ability to specify domain to use over Storefront when more than one domain is configured on Storefront.
* JMeter variables usage support in the Expected Value field on EndClause.
**Issues** https://github.com/Blazemeter/CitrixPlugin/issues/20
* Keystroke recording enhancements that allow you to record more complex keyboard combinations. 
**Issues** https://github.com/Blazemeter/CitrixPlugin/issues/30 and https://github.com/Blazemeter/CitrixPlugin/issues/34 
* InputText allows free text writing that generate complex keystrokes combinations automatically.  
**Issues**  https://github.com/Blazemeter/CitrixPlugin/issues/30 and https://github.com/Blazemeter/CitrixPlugin/issues/34
* Automatic disabling of Citrix Desktop Viewer, now it is not required to modify …
=> Citrix-Plugin Release 0.7.0

site/dat/repo/various.json
Source code at https://github.com/rbourga/jmeter-plugins-2.
=> Adding outlierdetector plugin to the repo list.

site/dat/repo/various.json
Alignment of version number in various.json with version number of jar file.
Fix of url in "Help on this plugin" link in UI .
=> Fixing of HelpLink and of jar version

site/dat/repo/blazemeter.json
Release 0.7.1
Enhancements:
* Interrupt detection is incorporated. New built-in error code SESSION_INTERRUPTED.
* A new UNKNOWN_ERROR error code is added when the source of the error is unknown.
* Wait for Logon removed from app startup.
* Image capture is retried when capture fails.
* Property "activeapp_timeout_ms" is incorporated, waiting time for the application to appear active.
* The default timeout of property "connect_timeout_ms" is increased to 90000ms.
* Improved handling of Logoff and Disconnect.
* Improvements in image capture when errors occur.
* When there are interaction errors, retries are canceled, improves times and minimizes log errors.
* Recorder stability improvement against unexpected errors.
* Setup: Java 9 support onwards.
=> Citrix-Plugin Release 0.7.1

site/dat/repo/blazemeter.json
=> RTE release 3.1.1

site/dat/repo/various.json
I hope you're doing fine !
Regards
=>  Release UbikLoadPack Video Streaming plugin 7.2.1

site/dat/repo/various.json
I hope you're doing fine and thanks again for your persistent reactivity and work on this.
Regards
=> Release UbikLoadPack Video Streaming plugin 7.2.2

site/dat/repo/various.json, site/dat/wiki/Contributors.wiki
Published a new release(1.1) for jmeter-pubsub-plugin
=> gcp-pubsub-1.1

site/dat/repo/various.json
Add awsmeter in jmeter-plugins.
=> Add awsmeter in jmeter-plugins

site/dat/repo/various.json
Support 'Markdown Table Data-driven' on GUI,Replace the 'While Controller'
=> release yongfa365-jmeter-plugin-1.0

site/dat/repo/blazemeter.json
Release 0.7.2
* Log the Get Text or Image Hash error when the error occurs from the UI.
* Verification of bzm.citrix.ocr_data_path parameter, the parameter is only approved if it is a Tesseract data folder.
Release 0.7.3
* Enabling Citrix Simulation API for older versions of Citrix Receiver
* JImageHash dependency updated to version 2.1.1
* Dialog size improvements in low screen resolution
* Improved button state handling in recorder.
* Empty value in Input Text is now allowed
=> Citrix-Plugin Release 0.7.2 and 0.7.3

site/dat/repo/various.json
I hope you're doing fine and thanks again for your persistent reactivity and work on this.
Regards
=> Release UbikLoadPack Video Streaming plugin 7.2.4

site/dat/repo/various.json
Hi @undera.
This PR is to publish new version of awsmeter .
Thank you.
=> Add new awsmeter version with AWS SNS Java Request samplers.

site/dat/repo/various.json
Consider ThreadGroup's setting: "Action to be taken after a Sampler error".
=> update various.json about yongfa365-jmeter-plugin

site/dat/repo/various.json
=> New ISO-8583 Sampler plugin version

site/dat/repo/blazemeter.json
Added the 1.1.2 version of Correlation Recorder plugin
=> Correlation Recorder Release 1.1.2

site/dat/repo/blazemeter.json
=> Updated dependencies for Correlation Recorder

site/dat/repo/various.json
=> release yongfa365-jmeter-plugin-2.0.1

site/dat/repo/blazemeter.json
Release 0.7.4
* Mouse event capture and playback improvements
* Retries when unexpected conditions occur
* Memory configuration added to Troubleshooting section
* Pre-recording or playback scaling preferences are disabled
=> Citrix-Plugin Release 0.7.4

site/dat/repo/various.json
This plugin compares results between two test runs using Cohen's d effect size.
The difference between the means is gauged from "Negligible" to "Huge" based on Sawilorsky's rule of thumb.
=> Adding Results Comparator plugin to the list.

site/dat/repo/various.json
Hello @undera,
Thank you in advance for your help and always for your reactivity ! and thanks again for your persistent reactivity and work on this project.
Regards
=>  Release UbikLoadPack Video Streaming plugin 7.2.8

site/dat/repo/various.json
Hello @undera,
Thank you in advance for your help and always for your reactivity ! and thanks again for your persistent reactivity and work on this project.
Regards
=> Release UbikLoadPack Video Streaming plugin 7.2.9

site/dat/wiki/HttpSimpleTableServer.wiki
Not sure of the wiki syntax and the final display result
=> Add STS parsing result and jmeter maven plugin configuration

site/dat/repo/various.json, site/dat/wiki/Contributors.wiki
Adding D-KafkaMeter plugin to extend Jmeter to performance evaluate Apache kafka
=> Added DI-KafkaMeter plugin

site/dat/repo/various.json, site/dat/wiki/Contributors.wiki
Added the missing dependency for pubsub 1.1 plugin
=> Pubsub Dependency added for v1.1

site/dat/wiki/ConcurrencyThreadGroup.wiki
Add dynamic_tg.shift_rampup_start  and dynamic_tg.temporisation properties documentation
=> Update documentation about properties

site/dat/repo/various.json
Hello @undera,
Thank you in advance for your help and always for your reactivity ! 
And thanks again for your persistent reactivity and work on this project.
Regards
=> Release UbikLoadPack Video Streaming plugin 8.0.1

site/dat/repo/various.json
- Add new `logResponseData` option for logging response data
=> Update Azure plugin to 0.2.7

site/dat/repo/various.json
Hello @undera,
And thanks again for your persistent reactivity and work on this project, and lot of success for your new project.
Regards
=> Release UbikLoadPack Video Streaming plugin 8.0.2

site/dat/repo/blazemeter.json
In this major release, have updated the jetty dependencies and deprecated some of the previous components. This version includes the following features:
- Support for GET, POST, PUT, PATCH, DELETE and OPTIONS methods
- Support for proxy usage
- Support for Header Manager, Auth Manager, Cookie Manager, and Cache Manager
- Support for follow redirect and automatically redirect
- Support for send files
- Support for GZIP responses
- Support for retrieve embedded resources
- General improvements like error management, reuse connections, timeouts handling
Warnings
- This version is compatible with java 11 or greater
- Test plans created with previous versions of the plugin are not supported, a feature to migrate from old test plans to the new version was implemented.
=> HTTP2 v2.0

site/dat/repo/various.json
Hi Team,
Please review and approve the merge request. I updated the JMeter gRPC Request version for https://github.com/zalopay-oss/jmeter-grpc-request/releases/tag/v1.2.0
Best Regards!
=> Update jmeter-grpc-request version in grpc-plugins

site/dat/repo/various.json
Hello @undera,
And thanks for your work on log4jshell fix !
Regards
=>  Release UbikLoadPack Video Streaming plugin 8.0.3

site/dat/repo/various.json
This PR will fix the version conflicts.
=> Validate Thread Group - Fix versions

site/dat/repo/various.json
modify baolu-csv-data-file-config display name and screenshotUrl
=> modify display name and screenshotUrl

site/dat/repo/various.json, site/dat/wiki/Contributors.wiki
This plugins provides additional features to CSV dataset to play around
=> Added Extended CSV dataset config plugin

site/dat/repo/various.json
Fixed Dependency download issue to download via plugins manager
=> Extended CSV dataset plugin

site/dat/repo/various.json
Fixed auto allocate issue
Fixed variable selector issue
=> Releasing extended csv dataset config 1.1

site/dat/repo/various.json
Fix the bug that the file cannot be found in the script relative directory in v1.2.1.
=> Baolu-csv-data-file-config v1.2.1

site/dat/repo/various.json
1.Format log output,remove unnecessary log printing to improve performance.
2.Completely solve the problem that the relative directory of the parameter file cannot be read.
=> Baolu-csv-data-file-config v1.2.2

site/dat/repo/various.json
=> Release UbikLoadPack Video Streaming plugin 8.0.5

site/dat/repo/blazemeter.json
Release 0.7.5
* New configuration GUI in Citrix Recorder
* New Template structure, with improvements in the initial configuration
* New popup oriented GUI always visible at the time of recording
* User documentation is updated and improved
* Update recommended version of OpenJDK to Adoptium OpenJDK 11.0.15_10
* Fixed errors in copy and paste and distributed execution on JMeter (RMI)
* New Download ICA Test Fragment with better Storefront support and with Citrix Gateway support
* Improvements on error control when the Storefront/Gateway process fail on recording
=> Citrix-Plugin Release 0.7.5

site/dat/repo/various.json
Sorry, copy and paste error :-)
=> Fix descriptor

site/dat/repo/various.json
New plugin for retrying failed samples
=> Publish Sample Retrier

site/dat/repo/various.json
Add jmeter atakama variabilization plugin to plugin manager
=> Add atakama plugin

site/dat/repo/blazemeter.json
Release 0.7.6
* New design of action buttons in recorder popup.
* Drop-down fits when opened at the edge of the screen.
* Error handling improvements.
* Update OCR engine (tess4j v5.2.1)
* Improved compatibility with new versions of Citrix Workspace
=> Citrix-Plugin Release 0.7.6

site/dat/repo/various.json
Add jmeter atakama backend listener
=> Add backend listener atakama

site/dat/repo/various.json
=> Support multithreading group.

site/dat/repo/blazemeter.json
- Add support to continue on unknown terminal command on TN3270
=> RTE Plugin release 3.2.2

site/dat/repo/various.json
Add new version 2.1.1 of awsmeter Jmeter plugin.
=> Add awsmeter version 2.1.1.

site/dat/repo/blazemeter.json
Add new version v1.2.2 of Correlation Recorder JMeter plugin.
=> Update v1.2.2 Correlation Recorder

site/dat/repo/various.json
Added couchbase plugin to the repo
=> Added couchbase plugin

site/dat/repo/various.json
Hello @undera,
First best wishes for 2023 !
This PR is to publish a new plugin for JMeter which allows monitoring a cli JMeter performance from browser.
Regards
=> Release UbikLoadPack Observability Plugin 1.0.1

site/dat/repo/various.json
This PR fixes a missing dependency when installing.
Thanks for your help
Regards
=> Release version 1.0.2 of UbikLoadPack Observability Plugin

site/dat/repo/various.json
Added DI Kafkameter 1.1 version
=> Added DI Kafkameter 1.1 version  

site/dat/repo/various.json
=>  Release UbikLoadPack Video Streaming plugin 8.0.6

site/dat/repo/various.json
Releasing new version of extended-csv-dataset-config 2.0
=> Releasing new version of extended-csv-dataset-config 

site/dat/repo/various.json, site/dat/wiki/Contributors.wiki
Fixed the serializer default value for producer
Updated error handling for client connections
=> Releasing DI Kafkameter v1.2

site/dat/repo/various.json
WS-Security plugin release 1.9
=> WS-Security plugin release 1.9

site/dat/repo/jpgc-tools.json, site/dat/wiki/HttpSimpleTableServer.wiki, tools/table-server/pom.xml, tools/table-server/src/main/java/org/jmeterplugins/protocol/http/control/HttpSimpleTableServer.java, tools/table-server/src/test/java/org/jmeterplugins/protocol/http/control/HttpSimpleTableServerTest.java
Command FIND with FIND_MODE : a string with SUBSTRING (Default) or EQUALS and a regular expression with REGEX_FIND (contains) and REGEX_MATCH (entire region the pattern)
=> Version 4.0 add command FIND a line in the filename

site/dat/repo/blazemeter.json
We're excited to bring you the latest enhancements and features in the Correlation Recorder Plugin v2.1 for JMeter. Here's what's new:
**BlazeMeter Correlation Cloud Integration:** 
Easily connect with your BlazeMeter account to access and utilize Correlation Templates saved in your Workspace. Plus, explore templates that come default with your BlazeMeter account.
**Enhanced Correlation Capabilities:**
Token Recognition: Boosted recognition of tokens during your recordings.
Regex Extractors: Enhanced the scope of generated extractors, now covering both Main and Sub Samples.
**User Interface (UI) Refinements:**
Repositories Configuration: Display the Repository’s Name for clearer understanding, rather than the endpoint’s URL.
Template Analysis Selection: Organized the display with a …
=> Correlation recorder 2.1

site/dat/repo/blazemeter.json
=> Citrix-Plugin Release 0.7.7

site/dat/repo/blazemeter.json
Added support for JMeter 5.6.x
=> HTTP2 plugin release 2.0.4

site/dat/repo/various.json
Added new release version for JWTPreProcessor plugin.
=> Added new release version for JWTPreProcessor plugin

site/dat/repo/jpgc-tools.json, site/dat/wiki/HttpSimpleTableServer.wiki
Http Simple Table Server 5.0 add new command READMULTI.
=> Http Simple Table Server v5.0

site/dat/repo/blazemeter.json
Correlation Recorder Plugin v2.2.1
- Rules editor.
- Rule catalog views.
- Rules suggestions.
- Rules save screen.
- Recording.
- Documentation.
Bugs have been fixed and greater stability has been achieved in recording and in the application of rules.
=> Correlation Recorder 2.2.1

site/dat/repo/various.json
Add vdn@github - elastic-apm-tool plugin
=> Add vdn@github - elastic-apm-tool

site/dat/repo/blazemeter.json
=> BlazeMeter Repositories 1.2

site/dat/repo/various.json
Version 5.0 har-convertor-jmeter-plugin. 
Add an external csv file with transaction information for JMeter Transaction Controller Name.  
Add compatibility with HAR generated with LoadRunner Web Recorder Chrome Extension.
=> Version 5.0 har-convertor-jmeter-plugin

site/dat/repo/various.json
fix issue with added think time after grouping http samplers
=> add HAR importer 0.2.1

site/dat/repo/blazemeter.json
We're excited to bring you the latest enhancements and features in the Correlation Recorder Plugin v2.5
Not everything is a regex, that's why it's possible to record a JSON flow and let the automatic correlation recorder handle the dynamic elements.
In this release, there is a new addition, every time the plugin encounters a dynamic value in a JSON response (possible extractor) or JSON request (possible replacement) it will be translated to a [JSON Extractor](https://jmeter.apache.org/usermanual/component_reference.html#JSON_Extractor) with it's JSON Path auto generated.
- Fixed an issue that avoided consuming boundary length for automatic regex generation
- Fixed an issue that avoided saving a template when fresh start the plugin
- Fixed an issue that showed …
=> Correlation Recorder v2.5

site/dat/repo/various.json
Hello @undera,
Thank you in advance for your help and involvement in JMeter community and as always for your reactivity !
Regards
=> Release UbikLoadPack Video Streaming plugin 9.1.5

site/dat/repo/blazemeter.json
We're excited to bring you the latest enhancements and features in the Auto Correlation Recorder Plugin v2.6
Auto Correlation Recorder has being enhanced with automatic URL encoding/decoding capabilities. The recorder can now detect URL-encoded data, automatically decode it, and replace it wherever it's used. It also supports the reverse process, handling decoded data that needs to be encoded for usage.
This improvement simplifies data management and reduces the need for manual adjustments.
- Fix issue which duplicates regular expression extractors
- Fix issue while installing the Auto Correlation Plugin causing to overwrite the JMeter templates.xml
- Fix wrong tooltip text description
- Fix correlation wizard opened in the back while changing modals
=> CorrelationRecorder v2.6

site/dat/repo/various.json
=> Add CORS Plugin

site/dat/repo/various.json
vdn-har-convertor-jmeter-tool v6.0 add View Result Tree to view the recording xml file.
=> Version 6.0 vdn-har-convertor-jmeter-tool

site/dat/repo/blazemeter.json
- Fix issue that couldn't provide responseFilters, components and dependencies in templates
- Update BZ SDK to comply with Blazemeter API
=> Release v1.3 Blazemeter Repository

site/dat/repo/blazemeter.json
We're excited to bring you the latest enhancements and features in the Auto Correlation Recorder Plugin v3.1
- Fixed wrong reporting of rules usage
- This caused that some extractors and replacements weren't applied correctly given the sense that rules weren't working
- Fixed order of suggestions generated
- This causes that the suggestions which get converted into rules were applied in a different order than the original template provided
- Now suggestions remain ordered as the rules template order.
- Add Waiting dialog while applying suggestions from template
- Add Waiting dialog while generating suggestions from template
- Waiting Dialogs can now being interrupted
- Interrupting suggestions appliance results in reset of testplan, keep in mind that suggestions needs …
=> CorrelationRecorder v3.1

site/dat/wiki/DummySampler.wiki
=> Update DummySampler.wiki - fix typo

site/dat/repo/various.json
Hello @undera,
Thanks for your reactivity.
This PR is to publish a new major version of UbikLoadPack Video Streaming plugin.
Thank you in advance
Regards
=>  Release UbikLoadPack Video Streaming plugin 10.0.0

site/dat/repo/various.json
Change the screenshoot for the plugin har-convertor-jmeter-tool
=> vdn-har-convertor-jmeter-tool change screenshoot

site/dat/repo/various.json
Add button 'MODIFY SCRIPT AND LOAD NEW SCRIPT' and choose only a jmx file not a directory
=> vdn@github - elastic-apm-tool Version 2.0

site/dat/repo/various.json
vdn-otel-apm-tool version 1.0, Apache JMeter tool plugin to Manage the integration of OpenTelemetry from Elastic Application Performance Monitoring in a JMeter script.
=> New plugin : vdn-otel-apm-tool version 1.0

site/dat/repo/various.json
update to java 17 (breaking change); including library updates for security/compatibility reasons
=> update har importer to v1.0.0

site/dat/repo/various.json
a change to also accept `Long` values, not only `Integer` in HAR files was merged:
https://github.com/sdstoehr/har-reader/pull/203#issuecomment-2824405818
and thus want to fix a User finding with it.
=> HarImporter Update

site/dat/repo/various.json
Hello @undera,
I hope you're fine.
This PR is to publish a new minor version of UbikLoadPack Video Streaming plugin.
Regards
=>  Release UbikLoadPack Video Streaming plugin 10.1.2
