undera/jmeter-plugins

- site/dat/wiki/Changelog.wiki
- standard/src/kg/apc/jmeter/vizualizers/AggregateReportGui.java
When it generated AggregateReport csv of jtl files on console, header of csv had 'aggregate_report_error%', but error ratio was no percentage value.
I apply format to CSVSaveSErvice, using StatGraphVisualizer same as other saveGraphToCSV function.
> Apply format to csv file (AggregateReportGui)

- site/dat/wiki/Changelog.wiki
- site/dat/wiki/UltimateThreadGroup.wiki
- standard/src/kg/apc/jmeter/threads/UltimateThreadGroup.java
- standard/test/kg/apc/jmeter/threads/UltimateThreadGroupTest.java
Per discussion in this thread: https://groups.google.com/forum/#!topic/jmeter-plugins/1vyLN_wjly8, this code pack contains support for configuring UltimateThreadGroup via external property "threads_schedule" to allow convenient test parametrization.
> Ultimate thread group upgrade

- site/dat/wiki/Changelog.wiki
- standard/src/kg/apc/jmeter/reporters/LoadosophiaUploader.java
- standard/test/kg/apc/jmeter/reporters/LoadosophiaUploaderTest.java
When a plugin is used to run on multiple environments, it is sometimes preferable that the storeDir is set to the system's default temp directory. I tried out not to set storeDir at all, but then i got a "premission denied" error because the code tries to set an trailing slash to an empty string resulting in "/" which is then passed to File.createTempFile("Loadosophia_", ".jtl", new File("/")); which results in an temp-file in the root directory. If run with unprivileged user, it will fail to create that file.
Why is it necessary to set storeDir? Why don't you use the system's temp folder in all cases?
> Fixed permission-denied-error on unix systems in LoadosophiaUploader

- standard/src/kg/apc/jmeter/vizualizers/SynthesisReportGui.java
<major>.<minor> but directly the revision like r1701891.
So don't use float to compare, use string
> For nightly build the jmeter version is not corresponding to pattern major.minor, use string to compare version

- site/dat/wiki/Changelog.wiki
- site/dat/wiki/Contributors.wiki
- webdriver/pom.xml
- webdriver/src/com/googlecode/jmeter/plugins/webdriver/config/RemoteCapability.java
- webdriver/src/com/googlecode/jmeter/plugins/webdriver/config/RemoteDesiredCapabilitiesFactory.java
- webdriver/test/com/googlecode/jmeter/plugins/webdriver/config/RemoteDesiredCapabilitiesFactoryTest.java
- webdriver/test/com/googlecode/jmeter/plugins/webdriver/config/RemoteDriverConfigTest.java
Since Selenium 2.33 there's the PhantomJS capability and adding this to JMeter-Plugins will enable it to run Headless Browser Testing using a Selenium Grid.
> (feature) Add basic PhantomJS capability to Remote WebDriver

- extras/src/org/jmeterplugins/protocol/http/control/HttpSimpleTableControl.java
- extras/src/org/jmeterplugins/protocol/http/control/HttpSimpleTableServer.java
- site/dat/wiki/Changelog.wiki
- site/dat/wiki/Contributors.wiki
- site/dat/wiki/FilterResultsTool.wiki
- site/dat/wiki/HttpSimpleTableServer.wiki
- site/dat/wiki/StandardSet.wiki
- standard/FilterResults.bat
- standard/FilterResults.sh
- standard/src/kg/apc/cmdtools/FilterResultsTool.java
- standard/src/kg/apc/jmeter/vizualizers/SynthesisReportGui.java
- standard/src/org/jmeterplugins/tools/FilterResults.java
- standard/zip.xml
Hi,
I add  FilterResults Tool launch with the "CMDRunner.jar --tool FilterResults"
Example : 
java  -jar %0\..\CMDRunner.jar --tool FilterResults --output-file filter.xml --input-file gestdoc_300sec.csv --include-label-regex true --include-labels "P[1-3].*" --start-offset 2 --end-offset 180 --success-filter true --save-as-xml true
This new tool need also modifications for the CMDRunner tool.
> Add command line Filter Results tool launch with CMDRunner tool

- site/dat/wiki/SettingsPanel.wiki
Links to these two PNG files are not getting rendered correctly into html by the wiki engine:
http://jmeter-plugins.org/img/wiki/settings/orangeSpectrum.png
http://jmeter-plugins.org/img/wiki/settings/labelToColorMapping.png
...at the bottom of this page:
http://jmeter-plugins.org/wiki/SettingsPanel/
Thanks,
--Erik
> trying to fix wiki to html translation problem

- tools/synthesis/src/main/java/kg/apc/jmeter/vizualizers/AggregateReportGui.java
There's 95% and 99%  response time data in aggregate report in GUI, but there's only 90%  response time data in command line.
For better data statistics, It'd be better to have 99% response time data.
> Add 95%, and 99% data in aggregate report

- plugins/json/src/main/java/com/atlantbh/jmeter/plugins/jsonutils/jsonpathassertion/gui/JSONPathAssertionGui.java
The text now reflects that the path is acutally checked and that its
checking is independent of the value check.
> Make UI text more clear

- infra/common/src/main/java/kg/apc/jmeter/graphs/AbstractMonitoringVisualizer.java
- infra/common/src/main/java/kg/apc/jmeter/vizualizers/MonitoringResultsCollector.java
- infra/common/src/main/java/kg/apc/jmeter/vizualizers/MonitoringSampleGenerator.java
- infra/common/src/main/java/kg/apc/jmeter/vizualizers/MonitoringSampleResult.java
- infra/common/src/main/java/kg/apc/jmeter/vizualizers/MonitoringSampler.java
- infra/common/src/test/java/kg/apc/jmeter/graphs/AbstractMonitoringVisualizerTest.java
- infra/common/src/test/java/kg/apc/jmeter/vizualizers/MonitoringResultsCollectorTest.java
- infra/common/src/test/java/kg/apc/jmeter/vizualizers/MonitoringSampleGeneratorTest.java
- infra/common/src/test/java/kg/apc/jmeter/vizualizers/MonitoringSampleResultTest.java
- infra/common/src/test/java/kg/apc/jmeter/vizualizers/MonitoringSamplerTest.java
- site/dat/repo/various.json
Several existing plugins such as JMXMon, DbMon, Perfmon use a common pattern for building the GUI as well as using a Collector class with a worker thread for collecting the monitoring samples (which use the Response Message field for the queried value).
This pattern should be generalized so that the above as well as future monitoring plugins can inherit the common behavior.
This pull request just adds those common classes (without refactoring existing plugins) for review by maintainers/contributors.
> Common base class for all monitoring plugins

- infra/common/src/main/java/kg/apc/jmeter/JMeterPluginsUtils.java
- infra/common/src/test/java/kg/apc/jmeter/JMeterPluginsUtilsTest.java
Most plugins have a help link on their title panel which is added via `JMeterPluginsUtils.addHelpLinkToPanel`.
However, this assumes that the help page is hosted on JMeter-Plugins.org and the URL is generated to point there, which does not work for external plugins.
In order for external plugins to still use the help link feature when subclassing common GUI classes (e.g. AbstractGraphPanelVisualizer etc) the help link should not be modified if it already is an (external) URL.
> Make GUI help link URL creation conditional

- site/dat/repo/various.json
_Not sure where or how I could add the plugin to the "Plugins manager", but I did find that ".json" file while scanning through the project._ 
The purpose of this plugin is to send sample results to an ElasticSearch engine to be able to monitor results through Kibana (or any other data visualizer that supports ElasticSearch). 
It also has support for build numbers if the tests are launched from Jenkins (only have to add a property "BuildNumber" with the %BUILDNUMBER%/$BUILDNUMBER variable).  This solution helps monitor response time over different builds.
> Added plugin 'ElasticSearch Backend Listener'

- site/dat/repo/various.json
Updated the JAR name of the "ElasticSearch Backend Listener" to resolve issue showing the plugin in "Has upgrades".
> ElasticSearch Backend Listener - Updated JAR Name

- plugins/json/src/main/java/com/atlantbh/jmeter/plugins/jsonutils/jsonpathextractor/JSONPathExtractor.java
This is to prevent spamming the log with warnings when the extraction fails and the default value is applied
> Change logging level when applying default JSON Path Extractor value

- site/dat/wiki/WebDriverTutorial.wiki
Page refers to "In the above example, the `Browser.get()`..." which initially confused me since I thought it referred to an example within the "Web Driver Sampler page" which is linked above.
The example is actually below this text.
> Minor wiki correction - WebDriverTutorial

- site/dat/repo/various.json
Fixed a bug where long test runs would trigger a crash caused by the connection pool of the OkHttp client
> Version 1.5.2 ElasticSearch Backend Listener

- site/dat/repo/various.json
* Added use of assertionArray
* getElapsedTime now returns a generic date for comparison in Jenkins AND the elapsed time according to today.
* Added "sentBytes" metric
* ResponseTime uses the getTime() method
* Added timeout to avoid hanging requests
* Corrected formatting of dates
* Added logging in case of failures
> Version 2.1.1 - ElasticSearch Backend Listener

- site/dat/repo/various.json
Versions below 2.1.0 are deprecated and should be updated to the latest. Also added version 2.2.1 which includes sampler filtering before sending to ElasticSearch.
> Added 2.2.1 and removed everything below 2.1.0

- plugins/tst/src/main/java/kg/apc/jmeter/timers/VariableThroughputTimer.java
- site/dat/wiki/ThroughputShapingTimer.wiki
Currently in logs we have:
2018-03-09 11:45:58,017 ERROR k.a.j.t.VariableThroughputTimer: Waiting thread was interrupted
java.lang.InterruptedException: null
at java.lang.Object.wait(Native Method) ~[?:1.8.0_131]
at kg.apc.jmeter.timers.VariableThroughputTimer.delay(VariableThroughputTimer.java:98) [jmeter-plugins-tst-2.2.jar:?]
at org.apache.jmeter.threads.JMeterThread.delay(JMeterThread.java:857) [ApacheJMeter_core.jar:4.0 r1823414]
at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:472) [ApacheJMeter_core.jar:4.0 r1823414]
at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:416) [ApacheJMeter_core.jar:4.0 r1823414]
at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250) [ApacheJMeter_core.jar:4.0 r1823414]
at …
> Try to cleanly stop threads before doing it abruptly to avoid pending samplers being interrupted

- plugins/tst/src/main/java/kg/apc/jmeter/timers/VariableThroughputTimer.java
- site/dat/wiki/ThroughputShapingTimer.wiki
Warning "No free threads available in current Thread Group" does not indicate which thread group is concerned.
Add this information.
> More details when not enough threads

- site/dat/repo/various.json
Added a new detail mode : "error" - only send the falling samplers to ElasticSearch
> Version 2.3.0 - ElasticSearch Backend Listener

- site/dat/repo/various.json
* Fixed an issue where filters wouldn't work with the newly added error mode
> 2.3.1 - ElasticSearch Backend Listener

- site/dat/repo/various.json
Added version 2.2.3 back for compatibility issues. People with older versions of the plugin won't be able to upgrade to the newest version.
> Added ES Backend Listener 2.2.3 back

- plugins/webdriver/src/main/java/com/googlecode/jmeter/plugins/webdriver/config/ChromeDriverConfig.java
- plugins/webdriver/src/main/java/com/googlecode/jmeter/plugins/webdriver/config/gui/ChromeDriverConfigGui.java
- plugins/webdriver/src/test/java/com/googlecode/jmeter/plugins/webdriver/config/ChromeDriverConfigTest.java
- plugins/webdriver/src/test/java/com/googlecode/jmeter/plugins/webdriver/config/gui/ChromeDriverConfigGuiTest.java
This expands on the ChromeDriver work in https://bugs.chromium.org/p/chromium/issues/detail?id=721739 to support Chrome Headless running in an environment with e.g. self-signed certs.
> Add Option to permit Insecure Certs in ChromeHeadless

- plugins/webdriver/src/main/java/com/googlecode/jmeter/plugins/webdriver/config/FileDetectorOption.java
- plugins/webdriver/src/main/java/com/googlecode/jmeter/plugins/webdriver/config/RemoteDriverConfig.java
- plugins/webdriver/src/main/java/com/googlecode/jmeter/plugins/webdriver/config/gui/RemoteDriverConfigGui.java
- plugins/webdriver/src/test/java/com/googlecode/jmeter/plugins/webdriver/config/RemoteDriverConfigTest.java
We have a requirement to upload files to a site under test via Selenium grid. In order to do this the remote web driver has to have the LocalFileDetector set (instead of the aptly named UselessFileDetector). 
I have added the option to select which file detector is used when creating the remote driver.
> Remote file detector option

- site/dat/repo/various.json
Fixes an issue where the ElasticSearch Backend Listener is always marked as being available (uninstalled) when it's false.
> Modified markerClass

- graphs/graphs-additional/src/main/java/kg/apc/jmeter/vizualizers/BytesThroughputOverTimeGui.java
I wrote a patch to get a sent bytes from SampleResult using a reflection to keep compatibility with JMeter 2.0. Could you apply this patch to the upcoming release??
> BytesThroughput Over Time does not support getSentBytes method in recent JMeter.

- plugins/webdriver/pom.xml
- plugins/webdriver/src/main/java/com/googlecode/jmeter/plugins/webdriver/config/FirefoxDriverConfig.java
- plugins/webdriver/src/main/java/com/googlecode/jmeter/plugins/webdriver/config/WebDriverConfig.java
- plugins/webdriver/src/test/java/com/blazemeter/jmeter/webdriver/phantomjs/PhantomJSDriverConfigGuiTest.java
- plugins/webdriver/src/test/java/com/blazemeter/jmeter/webdriver/phantomjs/PhantomJSDriverConfigTest.java
- plugins/webdriver/src/test/java/com/googlecode/jmeter/plugins/webdriver/config/ChromeDriverConfigTest.java
- plugins/webdriver/src/test/java/com/googlecode/jmeter/plugins/webdriver/config/FirefoxDriverConfigTest.java
- plugins/webdriver/src/test/java/com/googlecode/jmeter/plugins/webdriver/config/WebDriverConfigTest.java
- site/dat/repo/jpgc-plugins.json
Here is a new attempt to upgrade to Selenium 3. 
All unit tests are passing - except for PhantomJS, as I don't know how to setup on Windows. According to WebDriver PhantomJS is deprecated and should be replaced by Firefox/Chrome headless mode.
> Upgrade to Selenium 3.14

- site/dat/repo/blazemeter.json
Additionally, bam-rte 1.1 includes improved support for tn3270 protocol enhancements (sscp lu data, bid command) and fixes in screen representation and sending of server modified fields
> Add bzm-rte 1.1 which supports setting fields by label

- site/dat/repo/blazemeter.json
•Logo has been added.
•Plugin name has been changed to continue with the convention of BlazeMeter plugins .
•Issue in live stream when it did not show results in *View Results Tree* has been fixed.
> HLSPlugin v1.3

- site/dat/repo/various.json
This plugin is Listener with ability to send result to ClickhouseDB. It could send each Sampler-transation or aggregated Sampler-transaction info (averaged times, count of Sampler transactions etc.)
In additional, this plugin contains Classes for InfluxDB and ElasticSearch with Samplers aggregation ability.
Project link https://gitlab.com/testload/jmeter-listener
Wiki link https://gitlab.com/testload/jmeter-listener/wikis/home
>  Added plugin 'JMeter Listener pack'

- downloads.py
Handle optional quotes around filename when downloading Maven libs.
See https://groups.google.com/forum/#!topic/jmeter-plugins/wJDHJkoc98o
> Fix Maven download filenames

- site/dat/repo/various.json
This PR is to register our UbikLoadPack Autocorrelator plugin so that it's available through jmeter-plugins-manager.
We think we have provided required elements, but let us know if anything is missing.
Kudos to all your OSS work for the JMeter community.
Thanks
Regards
> Register UbikLoadPack Autocorrelator plugin on jmeter-plugins

- site/dat/repo/various.json
There was a typo in PR 357 on markerClass which leads Plugins manager to think plugin is not installed.
This PR fixes the issue.
Thank you for merging last one rapidly.
Regards
> Fix markerClass for UbikLoadPack Autocorrelator Plugin

- site/dat/repo/blazemeter.json
Hello,
This PR is to add this new plugin to Plugins-Manager. 
It allows performance testing Citrix exposed applications with Apache JMeter and automate testing of this technology:
- https://github.com/blazemeter/CitrixPlugin/
Thanks in advance for your time
Regards
> Add to plugins-manager the new Apache JMeter plugin for Citrix technology

- site/dat/repo/blazemeter.json
- site/dat/repo/various.json
- Support for `no SSL`, now the plugin is able to support HTTP2 protocol without an SSL certificate.
- Support for `PATCH` request method to ease partial modifications into a resource.
- Support for `DELETE` request method to facilitate deletes of a specified resource.
- All the dependencies were updated.
> Request methods PATCH & DELETE and no SSL support. Libraries updatead.

- site/dat/repo/blazemeter.json
- site/dat/repo/various.json
- Tabulator input support.
- Now you can create a new type of input called Tabulator Input, which will allow you instead of defining the coordinates, as usual, to send a value with differents amount of tabs before the input.
> RTE-Plugin: Tabulator input support.

- site/dat/repo/various.json
Our url had a parameter in the end "?c=1584900487" , it seems it does not work with plugins manager, the file written is ubik-jmeter-videostreaming-plugin-6.6.0.jar?c=1584900487 instead of ubik-jmeter-videostreaming-plugin-6.6.0.jar
So this PR removes this parameter.
We will try to provide a fix.
Regards
> Fix link with parameter not working with jmeter-plugins-manager

- site/dat/repo/blazemeter.json
- site/dat/repo/various.json
With this PR we are adding the following fixes:
- Fixed the playlist reload to keep working after interrupting a test and starting a new one.
- Fixed rounding issue when calculating reload time to allow for finer reload times.
- We included a jenv file to fix the java version to be used in dev environments using jenv.
> Added Patch 3.0.1 for HLS plugin

- site/dat/repo/various.json
Created a sampler to extend the Jmeter to support GCP pubsub
It can publish and subscribe messages from GCP pubsub
> Adding Jmeter-GCP-Pubsub-Sampler

- plugins/jmxmon/src/main/java/kg/apc/jmeter/jmxmon/JMXMonConnectionPool.java
- plugins/jmxmon/src/test/java/kg/apc/jmeter/jmxmon/JMXMonConnectionPoolTest.java
- site/dat/wiki/JMXMon.wiki
We almost always include a JMXMon listener in a test plan to monitor the JMeter JVM itself, to make sure there are no long garbage collection pauses or leaks etc.
Connecting JMXMon to the local JMeter JVM requires it to be started with Remote JMX enabled and a TCP port assigned, which can be problematic and is quite unnecessary.
This PR introduces the option to connect to the local JVM's MBeanServer.
This can be configured by specifying a special URL: an empty string.
> JMXMon - Add local JMeter connection option

- site/dat/repo/blazemeter.json
In this patch release, we fixed an issue that was causing no emulator interaction after setting the sample name while recording on VT protocol.
> RTE-Plugin v3.0.1

- tools/cmd/src/main/java/kg/apc/cmdtools/ReporterTool.java
- tools/cmd/src/main/java/kg/apc/jmeter/PluginsCMDWorker.java
- tools/cmd/src/test/java/kg/apc/cmdtools/ReporterToolTest.java
- tools/cmd/src/test/java/kg/apc/jmeter/PluginsCMDWorkerTest.java
Having possibility to label Y-Axis in performance tests tool making charts is a must. 
Otherwise each time report is sent, people are asking what are units on Y axis? Its According to my own experience with perf tests and this:
https://groups.google.com/forum/#!topic/jmeter-plugins/zjTwY38X_z8
https://groups.google.com/forum/#!searchin/jmeter-plugins/axis|sort:date/jmeter-plugins/C-mQuB_8PI8/Bdc6pNlyxNYJ
https://groups.google.com/forum/#!searchin/jmeter-plugins/axis|sort:date/jmeter-plugins/zjTwY38X_z8/s8pbcK-tmk8J
So I've added posibility to set Y-label using `--yAxisLabel <String>` option. If its not specified default String which is "Performance Metrics" like currently is used, so it shouldn't be breaking anything.
I made this change way to not disrupt other things, so if no …
> Added capability to set Y-Axis label on perfmon charts.

- site/dat/repo/blazemeter.json
BlazeMeter promotes a new convention in its name definition for its plugins.
Initially, the adaptation was requested to HLS, HTTP2, RTE, Correlation Recorder and Citrix plugins.
> New naming convention for BlazeMeter plugins

- site/dat/repo/various.json
Add Jmeter prometheus plugin as suggested here: https://github.com/johrstrom/jmeter-prometheus-plugin/issues/82
I've removed markerClass and componentClasses from the same as I'm not sure what they should refer to.
> Add Jmeter Prometheus plugin

- site/dat/repo/various.json
This PR is to publish a new version of [UbikLoadPack](https://ubikloadpack.com/video-streaming-performance.php) Video Streaming plugin.
Regards
> Release UbikLoadPack Video Streaming Plugin 7.1.6

- site/dat/repo/blazemeter.json
What's new on this minor release:
1. Fix issue when sending Attention Key on screens not constituted by fields. (TN5250 protocol)
1. **Add support for sending an attention key at a determined position**. This feature is very useful for scenarios where screens aren't constituted by fields, and there is a menu waiting for an ENTER key to be pressed on the desired position.
> In order to set the cursor position when building manually the TestPlan, would be adding a **Position Input** with the coordinates where we want to place the cursor, and then, is mandatory to set the value of the input, empty. The Recorder will do this automatically. For more information click [here](https://github.com/Blazemeter/RTEPlugin#sampler-rte-sampler)
1. Fix issue when the sample name kept changing when sending …
> RTE-Plugin minor release 3.1

- site/dat/repo/various.json
Adding new descriptor.
Plugins-Manager can apparently [handle ](https://github.com/undera/jmeter-plugins-manager/blob/dbdf810f2f6a323522d6f700e0da83c1144517f1/src/main/java/org/jmeterplugins/repository/Plugin.java#L360) non-existing `libs` element.
> Add HTTP Form Manager

- site/dat/wiki/HttpSimpleTableServer.wiki
Http Simple Table Server (STS) scripts examples can't be edit with Blockly, so remove Blockly.
> STS, Remove Blockly Editor because script can't be edit without error

- site/dat/repo/various.json
So that users running Java JRE 1.8 can execute the plugin.
> Setting Java compliance level to 1.8

- site/dat/repo/various.json
This makes the current version of the [SSH Sampler](https://github.com/yciabaud/jmeter-ssh-sampler) plugin available via the Plugins Manager.
Note: I'm not the author of that plugin.
> Add latest version of SSH Sampler

- site/dat/repo/various.json
Adding a new plugin for https://github.com/DataDog/jmeter-datadog-backend-listener/
I've tried to follow examples of other PRs in this repo, let me know if I got anything wrong.
I used the `DatadogBackendClient` class as the `marketClass` as it's the main one and is not expected to change.
For `componentClasses` I've listed a few other classes (but not all).
> Add datadog-backend-listener v0.1.0

- site/dat/repo/blazemeter.json
Now is possible to manually specify in sampler what is the protocol to be used while downloading the playlist!
By default, the sampler can automatically detect the protocol, but in some corner cases, the detection logic can't properly identify the protocol. In such scenarios, you can now manually specify which is the correct protocol.
Fix segment URL resolution for DASH live streamings which were previously generating incorrect timestamp values.
> Add HLS Release v3.1

- site/dat/repo/various.json
This plugin parses a JMeter results file and computes the Apdex score and rating of the samplers for a given satisfied threshold T, as per Apdex specs. No need to generate the Report Dash Board to get Apdex value!
As per Apdex specs, rating goes from "Unacceptable" to "Excellent", which should help in the decision of the test conclusion.
> Addition of a new Apdex Calculator plugin

- site/dat/repo/various.json
Hi Team,
Please review and approve the merge request. JMeter gRPC Request: https://github.com/zalopay-oss/jmeter-grpc-request
Thanks.
> Add jmeter-grpc-request in grpc-plugins

- site/dat/repo/blazemeter.json
Now is possible to separate your Correlation Rules into groups improving your testing capabilities:
Having a different set of rules separated into groups ease the testing due to the possibility of enabling and disabling them in bulk (applying its effect to the rules each contains)
Each group is self-managed, allowing to add, delete, disable and edit a set of rules without altering the rest of the correlations.
Other changes:
Now each Correlation Extractor/Replacement hide by default its advanced fields, displaying only the most used ones for a faster setup.
Improved the addition of custom extensions to your environment, by selecting "More" on each combo, a dialogue will allow you to interactively choose which extension want to use or remove.
> Release v1.2 Correlation Recorder

- site/dat/repo/blazemeter.json
What's new on this minor release
- Wait for disconnect support. 
- Now is possible to assert when a server disconnection occurs.
> E.g: Makes possible to validate the behave of a LOGOFF command.
- Automatic *Wait for Disconnect* recognition.
- When using the **Recorder** the **Terminal Emulator** will automatically detect for a server disconnection. Therefore a Wait for Disconnect is recorded and added to the current sampler.
- We have also fixed some issues:
- Frozen screen when recording TN3270 protocol.
- Not possible to send spaces as input.
> RTE Plugin release v3.2

- site/dat/repo/various.json
New released was cut here: https://github.com/DataDog/jmeter-datadog-backend-listener/releases/tag/0.2.0
> Add v0.2.0 of jmeter-datadog-backend-listener

- site/dat/repo/various.json
Hello @undera,
This PR is to publish a new version of UbikLoadPack Video Streaming plugin as explained here:
- https://www.ubik-ingenierie.com/blog/performance-testing-low-latency-hls-servers/
Thank you in advance for your help and always for your reactivity ! and thanks again for your persistent reactivity and work on this project.
Regards
>  Release UbikLoadPack Video Streaming plugin 8.0.0 with support for Apple Low-Latency HLS (LL-HLS)

- site/dat/repo/various.json
Hi Team,
Please review and approve the pull request. a ApacheJmeter assertion plugin to validate Sampler response field types based on JSON/YAML Schema. repo -> https://github.com/yeshan333/ApacheJmeter_Schema_Assertion
Thanks!
> Add ApacheJmeter Schema Assertion plugin

- site/dat/repo/various.json
Create a Backend listener which allows to send the JMeter metrics to Dynatrace. The implementation is located in Github.
See https://github.com/dynatrace-oss/jmeter-dynatrace-plugin for details.
> Added Dynatrace Plugin

- site/dat/repo/blazemeter.json
When another JMeter plugin auto-registers Jackson modules, it fails with exception:
> Uncaught Exception java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement in thread Thread[StandardJMeterEngine,5,main]. See log file for details.
> HLS Sampler: jackson-jaxb-annotations may require jaxb-api in some cases

- site/dat/repo/various.json
This plug-in supports automatic or manual csv data allocation for each thread.
It has a similar LoadRunner capability parameterization.
If your request involves database update operation, using this plug-in in the test script can avoid lock waiting and improve the reliability of test results.
> new plug-in baolu-csv-data-file-config

- site/dat/repo/various.json
Updating the Datadog plugin to 0.3.0. 
Note: Do not merge until https://github.com/DataDog/jmeter-datadog-backend-listener/pull/29 is merged and 0.3.0 is actually released.
> Add datadog-backend-listener v0.3.0

- plugins/functions/src/main/java/kg/apc/jmeter/functions/StrReplaceRegex.java
Key of the StrReplaceRegex function seems incorrect, it should be "__strReplaceRegex", not "__strReplace".
> __strReplaceRegex instead of __strReplace

- site/dat/repo/blazemeter.json
Added release for the HTTP2 v2.0.1 with improvements and fixes for max buffer size.
> HTTP2 v2.0.1

- site/dat/repo/blazemeter.json
This release has fixes for the following issues
https://github.com/Blazemeter/jmeter-http2-plugin/issues/24 To improve scalability: Changed the default configuration of handling threads and connections. Memory management in request is also changed to improve its management and eliminate memory allocation errors. The initialization process in interactions was changed to minimize stress on the system.
https://github.com/Blazemeter/jmeter-http2-plugin/issues/25 jMeter Property is incorporated to be able to assign the maximum waiting time for an idle connection.
https://github.com/Blazemeter/jmeter-http2-plugin/issues/26 The accept encoding and user agent headers that were assigned by default by Jetty are removed
https://github.com/Blazemeter/jmeter-http2-plugin/issues/36 Maximum Request …
> HTTP2 plugin release 2.0.2

- site/dat/repo/various.json
New version of the Datadog plugin (0.3.1) released.
> Add datadog-backend-listener v0.3.1

- site/dat/repo/various.json
This plugin has [had several releases](https://github.com/zalopay-oss/jmeter-grpc-request/releases) since the latest available in the plugin manager. Adding the latest version to the plugin repo.
> Add latest jmeter-grpc-request version

- site/dat/repo/jpgc-plugins.json
Have been having issues using CLI to install plugins such as json-lib which have ```http:// ``` in the URL endpoint, but no issue with endpoints which use ```https://```
Here is log example
```
2023-02-28 16:16:16,212 INFO o.j.r.JARSourceHTTP: Downloading: https://search.maven.org/remotecontent?filepath=org/seleniumhq/selenium/selenium-support/3.14.0/selenium-support-3.14.0.jar
2023-02-28 16:16:16,212 INFO o.j.r.PluginManagerCMD: Downloading selenium-support...
2023-02-28 16:16:16,275 INFO o.j.r.PluginManagerCMD: Downloaded selenium-support...
2023-02-28 16:16:16,275 INFO o.j.r.JARSourceHTTP: Downloading: http://search.maven.org/remotecontent?filepath=net/sf/json-lib/json-lib/2.4/json-lib-2.4-jdk15.jar
2023-02-28 16:16:16,275 INFO o.j.r.PluginManagerCMD: Downloading json-lib...
2023-02-28 …
```
> search.maven.org endpoints should be https

- plugins/redis/pom.xml
- plugins/redis/src/main/java/kg/apc/jmeter/config/redis/RedisDataSet.java
- plugins/redis/src/test/java/kg/apc/jmeter/config/redis/RedisDataSetTest.java
- site/dat/wiki/RedisDataSet.wiki
- Changed the default jedis commands to lmove + srandmember (4x performance improvement)
- Updated the redis mock library to support these commands
- Introduced new property for legacy support (redis version < 6.2.0)
- Cached polling strategy selection - replaced with Strategy pattern for extendability
- added dependencies for local development on m1 macs
> Added support for srandmember and lmove for queue-like polling [performance]

- site/dat/repo/various.json
Add tool.
This tool creates a JUnit XML file with KPI rules from JMeter JMeter Dashboard stats.json and generates a result file in JUnit XML format and other formats  : html, csv and json.
> add new tool vdn-junit-reporter-kpi-from-jmeter-dashboard-stats

- site/dat/repo/various.json
Add new tool.
This tool creates a JUnit XML file with KPI rules from JMeter CSV Report, export result in html, csv or json format
> add new tool vdn-junit-reporter-kpi-from-jmeter-report-csv

- plugins/tst/pom.xml
- plugins/tst/src/main/java/kg/apc/jmeter/timers/VariableThroughputTimer.java
- plugins/tst/src/main/java/kg/apc/jmeter/timers/VariableThroughputTimerGui.java
- plugins/tst/src/test/java/kg/apc/jmeter/timers/VariableThroughputTimerGuiTest.java
- plugins/tst/src/test/java/kg/apc/jmeter/timers/VariableThroughputTimerTest.java
- site/dat/wiki/ThroughputShapingTimer.wiki
- Added support for multiple load_profile properties for Throughput Shaping Timer ({name}.load_property
- Property is parsed in GUI on each name update and visible in preview (if named property exists)
- backwards compatible with load_profile property and GUI (if the named property is not defined) 
Name was used as identifier to keep the compatibility with tstFeedback function
> Feature/tst magic property fix [functional]

- site/dat/repo/various.json
Add new tool junit-reporter-kpi-compare-jmeter-report-csv.
Compare 2 results : current and reference.
This tool read KPI declarations in a file and apply the KPI assertion on 2 JMeter Report CSV files (current and reference) and generates a result file in JUnit XML format and others formats Html, Json and Csv.
> add new tool junit-reporter-kpi-compare-jmeter-report-csv

- site/dat/repo/various.json
Updated Rapi plugin for Jmeter to v1.0.1 
https://github.com/bobcode99/jmeter-rapi-plugin/releases/tag/v1.0.1
> Updated Rapi plugin for Jmeter to v1.0.1

- site/dat/repo/various.json
Updated Rapi plugin for Jmeter to v1.0.2
https://github.com/bobcode99/jmeter-rapi-plugin/releases/tag/v1.0.2
> Updated Rapi plugin for Jmeter to v1.0.2

- site/dat/repo/blazemeter.json
Added support for HTTP 1.x, ALPN, multiplexing, and parallel execution.
Also improvements in performance, memory and connection usage.
> HTTP2 plugin release 2.0.3

- site/dat/repo/various.json
New version of the Datadog plugin (0.5.0) released.
> Add datadog-backend-listener v0.5.0

- site/dat/wiki/HttpSimpleTableServer.wiki
- tools/table-server/pom.xml
- tools/table-server/src/main/java/org/jmeterplugins/protocol/http/control/HttpSimpleTableServer.java
- tools/table-server/src/test/java/org/jmeterplugins/protocol/http/control/HttpSimpleTableServerTest.java
STS version 5.0 add READMULTI command and correct bug with SAVE command ADD_TIMESTAMP=true
> Version 5.0 add READMULTI command

- plugins/redis/src/main/java/kg/apc/jmeter/config/redis/RedisDataSet.java
Fixing the Exception:  redis.clients.jedis.exceptions.JedisException: Could not return the broken resource to the pool
Which is triggered when jmeter calls testEnded() method. 
Evidence below:
I added a log to show the total number of idle connections before calling ``pool.destroy()`` at ``testEnded(String host)`` and noticed that the number of idle connections was equal to the number of exceptions. As we can see here:
Then I forced JMeter to consume all the connections before calling ``pool.destroy()``.
I know the problem is in Jedis itself, as it was already addressed in https://github.com/redis/jedis/pull/3353. The other possible solution would be updating the Jedis version, but I don't know if that would lead to any compatibility issue.
> [fix] - JedisException when test ends 

- site/dat/repo/various.json
Add a new importer that is able to take the browsers HAR files (HTTP Archive) and convert them into HTTP Samplers, Constant Timers, add cookies and headers and sort them into modules.
The motivation is to allow customers to record http requests without any knowledge of JMeter and without the hurdle of proxies.
@see https://github.com/Qytera-Gmbh/JMeterHARImporterPlugin/blob/main/README.md
> add initial version of HAR Importer

- site/dat/repo/various.json
Version 2.0 vdn@github - har-convertor-jmeter-tool.
For POST multipart/form-data don't put the content of the file in the Record.xml file because binary content could be large and not XML compatible. 
Add parameters : page_start_number and sampler_start_number to facilitate partial recording of website navigation.
> Update version 2.0 for vdn@github - har-convertor-jmeter-tool

- site/dat/repo/blazemeter.json
This release includes the following changes:
- Changed the behavior of the VT protocol to avoid waiting for server response in each character sent.
- Fixed an issue in VT protocol when trying to send special characters with Shift + key combination.
> RTE-Plugin v3.3 release

- site/dat/repo/various.json
vdn-har-convertor-jmeter-tool v3.1, use library har-to-jmeter-convertor-2.2 that correct bugs.
* Remove the header 'Content-length' because the length is computed by JMeter when the request is created. 
* POST or PUT could have query string and body with content so add query string to the path. 
* Set Content Encoding to UFT-8 for POST or PUT method and request Content-Type : application/json. 
* Add body data content in Record.xml for PUT and PATCH methods.
> vdn-har-convertor-jmeter-tool v3.2

- site/dat/repo/various.json
- The importer has a host exclude list now
- Added multiple options for elements to be added or excluded.
- Groups http samplers into the same transaction controller, if they were recorded at the same time.
> HAR Importer v0.2.0 added

- site/dat/repo/blazemeter.json
We're excited to bring you the latest enhancements and features in the Auto Correlation Recorder Plugin v2.5.1
Lately the project have changed its path to an automatic paradigm. Therefore an appropriate name was chosen.
It's possible to see how the rebranding took effects in [Official Documentation](https://blazemeter.github.io/CorrelationRecorder/), [JMeter Plugins](https://jmeter-plugins.org/?search=Blazemeter%20-%20Auto%20Correlation%20Recorder%20Plugin) and Auto Correlation Plugin components!
A feature was added in order to be able to use rules that are under development, inside of the correlation rules tab.
Forget about saving a template version every time you want to give a try your new set of rules. 
Performance was a big deal when dealing with large recordings. …
> CorrelationRecorder v2.5.1

- plugins/tst/src/main/java/kg/apc/jmeter/timers/VariableThroughputTimer.java
We found an issue when running tests in Kubernetes environment that tests finished unexpectedly before time. For 12h tests it ends after 8h sometimes 10h. After this change where we are fetching elapsed time from JVM instead of POD OS issue is not reproducing anymore.
> Fix for Throughput Shaping Timer for unexpected test break before configured time

- site/dat/repo/various.json
Add Pacing to JMeter, compute a pause for the pacing duration since thread start iteration or since start time in a variable. New samplers
1) Pacing Start Sampler
2) Pacing Pause Sampler
> Add new pacing-jmeter-plugin v1.0

- site/dat/repo/blazemeter.json
We're excited to bring you the latest enhancements and features in the Auto Correlation Recorder Plugin v3.0
The following components were removed from the plugin
- Siebel Array JMeter Function
- Siebel Counter Correlation Replacement
- Siebel Row Correlation Extractor
- Siebel Row Id Correlation Replacement
- Siebel Row Params Correlation Replacement
The main reason this release is major one is due to the lack of backward compatibility.
However, not all are bad news. Now it's possible to access to a better Siebel correlation support by joining the [Blazemeter community](https://www.blazemeter.com/).
It's possible to use the new template and components directly from the plugin!
- Fix issue which reseted the JMeter templates.xml
- Allow to display templates description …
> CorrelationRecorder v3.0

- site/dat/repo/jpgc-plugins.json
Support for 'Same User On Each Iteration' on ConcurrencyThreadGroup, ArrivalsThreadGroup and FreeFormArrivalsThreadGroup
> Custom Thread Groups v3.0

- site/dat/repo/various.json
Version 6.1 Use new library har-to-jmeter-convertor 6.1 to correct a NullPointerException when creating the Recording XML file.
> Version 6.1 for har-convertor-jmeter-tool

- site/dat/repo/various.json
Version 7.0, Use new library har-to-jmeter-convertor 7.0 add manage the websocket connection and messages with 'WebSocket Samplers by Peter Doornbosch', add checkbox for boolean parameter 'ws_with_pdoornbosch' (default unchecked == false).
> Version 7.0 plugin 'har-convertor-jmeter-tool', add WebSocket

- site/dat/repo/blazemeter.json
We're excited to bring you the latest enhancements and features in the Auto Correlation Recorder Plugin v3.1.1
This release is a minor update to reflect the recent rebranding of BlazeMeter to Perforce within the ACR. 
We understand that there are other issues in the backlog, but this update has been prioritized to maintain brand consistency.
Stay tuned for upcoming releases!
> Blazemeter/CorrelationRecorder release v3.1.1

- site/dat/repo/jpgc-plugins.json
IteratingController support for built-in iteration variable support in JMeter 5.2+
Hi @undera 
Yesterday, the PR related to version 3.1 of Custom Thread Groups was approved.
I didn't find that it's yet available in Maven.
This PR depends on the JAR being available in Maven.
I'll leave it up to you to tell me the steps to follow to have version 3.1 in production.
> Custom Thread Groups v3.1

- site/dat/repo/various.json
Update tools vdn@github :
- junit-reporter-kpi-compare-jmeter-report-csv v1.4
- junit-reporter-kpi-from-jmeter-dashboard-stats v1.5
- junit-reporter-kpi-from-jmeter-report-csv v1.7
Change page title, define unique table css class to avoid conflict between tools.
> Update 3 tools vdn-junit-reporter-kpi-xxx

- plugins/casutg/pom.xml
- plugins/casutg/src/main/java/com/blazemeter/jmeter/control/VirtualUserController.java
In version 3.1 of Custom Thread Groups, support for iteration variables was added.
It was reported that now that the iteration variable is reported, it doesn't follow the same pattern as ThreadGroup.
VirtualUserController has a different iteration numbering logic, which is why the first iteration is initialized with 1.
Therefore, when updateIterationIndex is called to store the iteration variable with the _idx value, it starts at 1, not 0 like ThreadGroup.
A small fix has been made to report it so that VirtualUserController reports the same way as the ThreadGroup controller (The iteration index is reported starting at zero).
It is proposed to adjust how the value is reported to updateIterationIndex so that the index used in the variables is appropriate, starting from zero.
Also fixed …
> Custom Thread Groups - Reporting the correct value to updateIterationIndex

- site/dat/repo/jpgc-plugins.json
Minor fix related to IteratingController support and reported starting index
Hi @undera
Today, the PR related to version 3.1.1 of Custom Thread Groups was approved.
This PR is to be reviewed and executed when the maven release of Custom Thread Groups version 3.1.1 is complete.
> Custom Thread Groups v3.1.1

- site/dat/repo/blazemeter.json
- This release includes the usage of the [jmeter-bzm-commons](https://github.com/Blazemeter/jmeter-bzm-commons)
- A module that enables to reuse logic shared along all BlazeMeter maintained plugins
> Blazemeter/jmeter-http2-plugin release v2.0.6

- site/dat/repo/blazemeter.json
- BlazeMeter rebranding
* Add JMeter Plugin publish action by @Baraujo25 in https://github.com/Blazemeter/HLSPlugin/pull/34
* Remove testing upstream from automatic release deployment by @Baraujo25 in https://github.com/Blazemeter/HLSPlugin/pull/36
* Release v3.2.1 by @Baraujo25 in https://github.com/Blazemeter/HLSPlugin/pull/35
**Full Changelog**: https://github.com/Blazemeter/HLSPlugin/compare/v3.2...v3.2.1
> Blazemeter/HLSPlugin release v3.2.1

- site/dat/repo/blazemeter.json
Hot-fix missing dependency on VideoStreaming Plugin
> Add blazemeter commons dependency to latest VideoStreaming Plugin

- site/dat/repo/blazemeter.json
Release 0.7.8
- Blazemeter icon updated (via jmeter-bzm-commons update)
- Fixed a Null Pointer Exception that prevented the plugin from being used in batch mode.
- The citrix_client_name variable can now be used in both recording and batch modes.
> Blazemeter/CitrixPlugin release v0.7.8

- plugins/autostop/pom.xml
- plugins/autostop/src/main/java/kg/apc/jmeter/reporters/AutoStop.java
- plugins/autostop/src/main/java/kg/apc/jmeter/reporters/JAutoStopPanel.form
- plugins/autostop/src/main/java/kg/apc/jmeter/reporters/JAutoStopPanel.java
- plugins/autostop/src/test/java/kg/apc/jmeter/reporters/AutoStopTest.java
- site/dat/wiki/Contributors.wiki
Added auto-stop feature based on percentile value for response time. 
Considering micro-services, this feature is helpful for latency sensitive application's where P95 and P99 are used to determine SLA breeches and stop the load automatically with the help of this plugin
> Enhancements Jmeter autostop plugin

- site/dat/repo/blazemeter.json
* Bump log4j-core from 2.8.2 to 2.15.0 by @dependabot[bot] in https://github.com/Blazemeter/jmeter-debugger/pull/16
* Apply blazemeter rebranding by @Baraujo25 in https://github.com/Blazemeter/jmeter-debugger/pull/23
* @dependabot[bot] made their first contribution in https://github.com/Blazemeter/jmeter-debugger/pull/16
* @Baraujo25 made their first contribution in https://github.com/Blazemeter/jmeter-debugger/pull/23
**Full Changelog**: https://github.com/Blazemeter/jmeter-debugger/compare/0.6...0.6.1
> Blazemeter/jmeter-debugger release v0.6.1

- site/dat/repo/blazemeter.json
***What's new on this patch release:***
- BlazeMeter Rebranding
- Documentation updated to impact BlazeMeter rebrand
- Icons in the Terminal Emulator have now been restored
- Automatic deployment to JMeter Plugins enabled
- Automatic deployment to Maven Central enabled
**Traceable Changelog:**
* Release v3.3.1 by @Baraujo25 in https://github.com/Blazemeter/RTEPlugin/pull/44
* Comply with maven central requirements for deployment by @Baraujo25 in https://github.com/Blazemeter/RTEPlugin/pull/46
* Add jmeter plugin publish action by @Baraujo25 in https://github.com/Blazemeter/RTEPlugin/pull/45
**Full Changelog**: https://github.com/Blazemeter/RTEPlugin/compare/v3.3...v3.3.1
> Blazemeter/RTEPlugin release v3.3.1
